branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  subredditluna-env1:
    branch: master
    repository: subreddit
global:
  application_name: subreddit20
  branch: master
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: subreddit20
  sc: git
  workspace_type: Application
